Server application generation
NikitinaEkaterina/nikitina_backend pull request #1
Opened 2022-07-19 11:01 UTC by NikitinaEkaterina

2022-07-19 11:47 UTC, dsulimenko commented
![image](https://user-images.githubusercontent.com/78342339/179742735-eeea7ee0-041c-47ce-be9d-dee9ad6a0aa4.png)
Надо занятся гитигнором

2022-07-19 13:12 UTC, dsulimenko commented
и снова не все в игноре
![Selection_564](https://user-images.githubusercontent.com/78342339/179758667-b410a26a-f8bc-4d57-8c45-8ae45f8263d8.png)

2022-07-19 13:13 UTC, dsulimenko commented on nikitina_backend/newsSiteApp/tests.py
> +
ты не используешь этот файл

2022-07-19 14:01 UTC, skaptelinin commented
Общее замечание - в проекте должен быть файл с зависимостями. Например, на фронте npm умеет это из коробки. Если в проекте используется `pip`, нужно выполнить команду
`pip freeze > requirements.txt`
Вот еще несколько полезных вещей
https://note.nkmk.me/en/python-pip-install-requirements/

2022-07-19 14:13 UTC, skaptelinin commented on nikitina_backend/newsSiteApp/models.py
> +class User(models.Model):
В Django есть готовая модель пользователя
`from django.contrib.auth.models import AbstractUser`
Там есть хэширование пароля, проверка на уникальность имейла и куча других полезных вещей. Можно отнаследовать модель юзера от него, и оставить только аватар.

2022-07-19 14:16 UTC, skaptelinin commented on nikitina_backend/newsSiteApp/models.py
> +    avatar = models.TextField
Аватар - это файл, в джанго есть специальные поля для работы с ними. Здесь нужно использовать models.ImageField()

2022-07-19 14:16 UTC, skaptelinin commented on nikitina_backend/newsSiteApp/models.py
> +    tittle = models.CharField(max_length=100)
очепятка)

2022-07-19 14:25 UTC, skaptelinin commented
имя директории newsSiteApp в camelCase. Обычно названия директорий пишутся snake_case

2022-07-19 14:26 UTC, skaptelinin requested changes

2022-07-19 14:26 UTC, skaptelinin commented on nikitina_backend/newsSiteApp/serializers.py
> +
Общее замечание по pep8:
1. Нет разделения импортов по built-in libraries, third-party libraries, project dependencies. Например, между импортами сериалайзеров из рест фреймворка и моделей должна быть пустая строка
2. Классы должны разделяться двумя пустыми строками, методы должны разделяться одной пустой строкой
3. Рекомендуется писать документацию к каждому классу. Требование необязательное, но лучше привыкать это делать.

2022-07-20 08:03 UTC, skaptelinin requested changes

2022-07-20 08:03 UTC, skaptelinin commented on .gitignore
> +migrations/__pycache__
Для .gitignore лучше брать готовые шаблоны, потому что там очень много вещей может оказаться. Можно использовать в качестве примера https://github.com/jpadilla/django-project-template/blob/master/.gitignore

2022-07-20 08:03 UTC, skaptelinin commented on nikitina_backend/newsSiteApp/migrations/0001_initial.py
> +
Гитхаб пишет, что этот файл был изменен. Файлы миграций не нужно трогать, они нужны только для обновления таблиц в бд

2022-07-20 08:03 UTC, skaptelinin commented on nikitina_backend/newsSiteApp/models.py
> +    email = models.EmailField(max_length=255, unique=True)
Поля username, password и email уже есть в AbstractUser, их не нужно переопределять

2022-07-20 08:52 UTC, skaptelinin approved these changes

2022-07-20 09:01 UTC, merged